services:
  - type: web
    name: madison-magazine
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn magazinep.wsgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    runtime:
      pythonVersion: 3.10
pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
