# Generated by Django 5.2 on 2025-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_articles_slug_alter_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs/'),
        ),
    ]
