# Generated by Django 5.2 on 2025-04-30 09:03

from django.db import migrations


def assign_default_category(apps, schema_editor):
    Articles = apps.get_model('myapp', 'Articles')
    Category = apps.get_model('myapp', 'Category')
    
    # Get or create default category
    default_category, created = Category.objects.get_or_create(
        name="Uncategorized",
        defaults={'description': 'Default category for uncategorized articles'}
    )
    
    # Update all articles without a category
    Articles.objects.filter(category__isnull=True).update(category=default_category)

def reverse_func(apps, schema_editor):
    pass
# In a new migration file
from django.db import migrations

def create_initial_plans(apps, schema_editor):
    Plan = apps.get_model('your_app_name', 'Plan')
    
    Plan.objects.get_or_create(
        name='Free',
        defaults={
            'description': 'Basic free plan',
            'price': 0,
            'duration_days': 0,
            'features': {
                'read_articles': True,
                'comment': True,
                'ad_free': False,
                'exclusive_content': False
            }
        }
    )
    
    Plan.objects.get_or_create(
        name='Premium',
        defaults={
            'description': 'Premium monthly plan',
            'price': 100,
            'duration_days': 30,
            'features': {
                'read_articles': True,
                'comment': True,
                'ad_free': True,
                'exclusive_content': True
            }
        }
    )
    
    Plan.objects.get_or_create(
        name='Premium 6 Months',
        defaults={
            'description': 'Premium 6 month plan',
            'price': 600,
            'duration_days': 180,
            'features': {
                'read_articles': True,
                'comment': True,
                'ad_free': True,
                'exclusive_content': True
            }
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userplan_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_default_category, reverse_func, create_initial_plans),
    ]
