# Generated by Django 5.2 on 2025-05-05 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_articles_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_link',
        ),
        migrations.AddField(
            model_name='articles',
            name='ai_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='read_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='No message content'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Untitled Notification', max_length=255),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
