# Generated by Django 5.2 on 2025-05-05 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_articles_description_remove_articles_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='myapp.articles'),
        ),
    ]
