# Generated by Django 5.2 on 2025-05-06 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userinteraction_liked_userinteraction_viewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='ai_approved',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='views',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_url',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='viewed',
        ),
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_alt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('article', 'New Article'), ('comment', 'New Comment'), ('announcement', 'Announcement'), ('subscription', 'Subscription Update')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.articles'),
        ),
    ]
