# Generated by Django 5.2 on 2025-05-06 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_articles_ai_approved_remove_articles_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='reading_level',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Advanced')], default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='timestamp',
            field=models.DateTimeField(default=timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'article', 'interaction_type')},
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scroll_depth', models.FloatField(default=0)),
                ('time_spent', models.FloatField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReadingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_reading_speed_wpm', models.FloatField(default=200)),
                ('preferred_reading_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Advanced')], default=2)),
                ('preferred_tags', models.ManyToManyField(to='myapp.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='myapp.tag'),
        ),
    ]
