# Generated by Django 5.2 on 2025-05-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_tag_article_reading_level_article_word_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
