# Generated by Django 5.2 on 2025-05-07 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_userinteraction_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AddField(
            model_name='readingsession',
            name='words_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreadingprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserReadingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.PositiveIntegerField(help_text='Time spent in seconds')),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('scroll_depth', models.FloatField(default=0.0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'last_read'], name='myapp_userr_user_id_654094_idx'), models.Index(fields=['article', 'time_spent'], name='myapp_userr_article_ff87e9_idx')],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
