# Generated by Django 5.2 on 2025-05-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='scroll_depth',
            field=models.FloatField(default=0.0),
        ),
    ]
